### ISSUE TITLE
Jokermon storage isn't working

### ISSUE THREAD

**Issue by Ravenous212** [segabl/pd2-jokermon#1]
Converting cops isn't adding them the jokermon list for whatever reason, the mod appears in the list and the window itself will open without issue, it just won't save converted cops.

Wasn't working before or after storage limit was added.

**Comment by segabl** [comment]
Do you have any other mods that affect jokers?

**Comment by Ravenous212** [comment]
Less BS OneDown, Convert Gangsters (doubt it), Full Speed Swarm, Keepers+Joker names, Joker masks, Replace jokers, The Fixes and Crime Spree modifiers as mutators, though none were active at any point...

We both tested with and without all of these and nothing changed, in fact there's a number of these in the list that he doesn't use due to crashing issues relating to other mods yet Jokermon works fine for him, no idea why it's refusing to work for me.

**Comment by segabl** [comment]
Was this all with you being client or host? Did you try both? If the rest of the mod functions then it is probably an issue with some other mod overriding the convert function and Jokermon not receiving the notification of a joker conversion therefore.

**Comment by Ravenous212** [comment]
All hosting, both online and offline, I'll be trying as a client whenever I'm able to get back on the game.

**Comment by segabl** [comment]
You could use something like Notepad++ to search all files in your mod directory for mods that change the function `convert_hostage_to_criminal` which is the main function that triggers most of Jokermon's code.

**Comment by Ravenous212** [comment]
Figured out the problem, despite adding and removing it over and over, Intimidated outlines is causing the issue, removed it before and the issue still persisted, so I don't know what else was possibly causing it, but it's working now.

**Comment by segabl** [comment]
Good to know you managed to get it working. I don't know if intimidated outlines is still maintained, but you could add the issue there so they can improve it
