### ISSUE TITLE
Jokermon CTD on Startup

### ISSUE THREAD

**Issue by ShadowKnight849** [segabl/pd2-jokermon#11]
Whenever I attempt to start Payday 2 with Jokermon installed, the game instantly crashes to desktop after briefly seeing the loading screen. 

I've attempted a full reinstall to no avail.

SuperBLT and BeardLib are both installed and function fine, but when attempting to start the game with Jokermon, the game crashes.

**Comment by ShadowKnight849** [comment]
[crash.txt](https://github.com/segabl/pd2-jokermon/files/7081594/crash.txt)

**Comment by segabl** [comment]
`mods/pd2-jokermon-master/mod.lua:1086: attempt to index global 'HopLib' (a nil value)`

This crash tells me you missed a dependency.

**Comment by ShadowKnight849** [comment]
Just checked and it appeared I did infact, forget to install HopLib.

Thank you!
