### ISSUE TITLE
Jokers not spawning client side

### ISSUE THREAD

**Issue by KobiiKobes** [segabl/pd2-jokermon#2]
I cant spawn jokers client side any more. Is this intended? I loved messing around with my friend with this mod we both use it and see what npcs we can grab outa other hiests.

**Comment by segabl** [comment]
Make sure you both have the newest version, as I changed some variable names. It should still work for clients if the host has the mod

**Comment by KobiiKobes** [comment]
I will try deleting and reinstalling i am on the newest version i believe but i will try that and see if it helps

**Comment by segabl** [comment]
Closing this as I can't reproduce the issue
