### ISSUE TITLE
Joker info bars stuck on screen

### ISSUE THREAD

**Issue by Ravenous212** [segabl/pd2-jokermon#4]
Not sure if it's an issue related to the "Replace Jokers" mod or just an issue with temporary mode and public sessions, but jokers health bars tend to get stuck on screen after they die when trying to replace them if they still have health left, sometimes randomly dying while still having health left as well, though the latter I believe to be unrelated: 
![image](https://user-images.githubusercontent.com/26052230/83956117-f0cbb500-a830-11ea-979e-3202dd7e7da6.png)

Names also tend to bug out, basically copying the first one converted regardless of what the unit actually is, can't seem to figure that one out at all, names don't get overwritten by the looks of it if they're custom made in the menu.

**Comment by Ravenous212** [comment]
This seems like it actually might be related to the second joker slot when as a client, can't quite tell as it's being inconsistent, sometimes it works and sometimes it fails... temporary mode or not.

EDIT: Nope, not related to the second joker slot, panel just breaks in public sessions when as a client and refuses to remove itself from the hud... still can't figure out if it's related to the Replace Jokers mod or not... but seeing as it's only happening in public games as client, probably worth looking into...

**Comment by segabl** [comment]
It happens sometimes as client unfortunately. I haven't found a way to fix it yet. It seems to be a combination of connection delay and wonky game code. That said, if it happens a lot to you I could imagine that replace jokers is contributing to it.

**Comment by Ravenous212** [comment]
Seems to happen regardless of Replace Jokers, and the only current workaround is turning off the panels when on temporary mode.

EDIT: Could it be related to the jokers health client side attempting to scale up to the difficulty and failing to register them as correctly dead? Seeing as the mod scales the level up to whatever difficulty your playing on, it would make sense if it didn't immediately get set to zero upon taking a fatal hit from whatever damage source hit it, really confusing...

**Comment by segabl** [comment]
Definitely something that could be related to unsynced hp, although killing shots usually don't get synced as "X damage was done to Y" but rather as "Y died" so each client will kill a unit independently of their remaining hp.

**Comment by Ravenous212** [comment]
After screwing around with it, I've come to the conclusion that it IS the health scaling causing it, why? Hell if I know, tack another for payday 2's spaghetti code, either way it ALWAYS seems to be jokers with higher health bars than the host of the game see's that break the hud, it very rarely removes itself correctly and Replace Jokers has nothing to do with it seeing as I've had multiple sessions where i completely forgot to do anything with it and it's still happened regardless... my only guess would be the hud elements are registering the damage wasn't enough to kill and failing to remove because of that, otherwise, I'm clueless... possibly related to players killing them.

**Comment by segabl** [comment]
I will put some checks in place that prevent the HP from being changed if the host doesn't use the mod. That's something I've wanted to do anyways at some point. May take some time though.

**Comment by Ravenous212** [comment]
Could possibly add something that checks if the value is at 0 and forcefully remove the hud elements if that doesn't work, or add a keybind to do so, something like that.

**Comment by segabl** [comment]
I included a potential quick fix in the most recent update, let me know if the issue is still occuring for you.

**Comment by Ravenous212** [comment]
So far, hasn't gotten stuck on screen, not calling it fixed yet, giving it a couple days... but seeing as I've had a friend intentionally set up the desync and not one single time did the health bar get stuck on screen, however I'm unsure of if latency will do anything to it but I *think* it's fixed.

If there's a way to tell, it's the test of time, hopefully it's snuffed out for good.

**Comment by Ravenous212** [comment]
Panels haven't gotten stuck on screen since the fix, think it's safe to say it's good.

**Comment by segabl** [comment]
Great, feel free to reopen the issue in case it somehow happens again.

**Comment by Ravenous212** [comment]
Uhh... ![20200622180250_1](https://user-images.githubusercontent.com/26052230/85335062-bf025180-b4b2-11ea-847e-97f3904f4a41.jpg)
I'm not exactly sure what happened here but I'm pretty sure it was lag related... any ideas?

**Comment by Ravenous212** [comment]
Looks to be directly related to converting during packet loss with the host, not sure how fixable that is...

**Comment by segabl** [comment]
so the panels all appeared when you converted one cop?

**Comment by Ravenous212** [comment]
Yeah, it happens during packet loss with the host while as a client, not sure if it's fixable but happened twice, that being the only reason I know it's lag related... Wolfhud also only registers one joker in the top right, that being my panel spawning wizard lol

Tried using Replace Jokers to remove the panels since they were all caused by one joker, didn't seem to work, couldn't test the second one because of losing connection due said hosts constant lag and packet loss...

**Comment by Ravenous212** [comment]
Sorry to necro this but I take it this isn't fixable without screwing around with more invasive code than preferred... it's entirely netcode related I think, since you don't have it happen while hosting or offline... also is it possible to prevent jokers names from being over-written by other jokers names when deployed? If you want that second one in a new thread, just say...

**Comment by segabl** [comment]
How often does this still happen to you? And I'm not sure what you mean with the names being overwritten? It can happen in rare occasions when the game spawned a different unit than the mod expected, but it should not change their name permanently.

**Comment by Ravenous212** [comment]
Not often since I mainly host now due to other mods that improve the experience, the names changing seem to happen sometimes when spawning and despawning jokers but I no idea why, but it might be related to converting one on the map/spawning one first and vice versa... not 100% sure.

**Comment by segabl** [comment]
So does the panel duplication only happen when you spawn one joker manually or when you convert a new one? or both?

**Comment by Ravenous212** [comment]
I haven't done a controlled test of summoning jokers, but converting one when the connection between the host and the client in question is laggy causes it to my knowledge, hence my saying not sure if it's something you can fix.

**Comment by segabl** [comment]
Ok it might be that the game executes the function multiple times when it's laggy and that causes the Hook to fire multiple times too. I added a very basic check in the latest update, let me know if that helped.

**Comment by Ravenous212** [comment]
It's most likely because the client needs to confirm with the host that there's a convert, and it sends it multiple times during latency, like chat messages...

**Comment by Ravenous212** [comment]
There's now a minor incompatibility with replace jokers that causes both jokers to die upon a reconvert... not that bad, but still annoying, only happens as a client though, works normally otherwise.

**Comment by segabl** [comment]
That shouldn't be something caused by the latest update though.

**Comment by Ravenous212** [comment]
It's only as a client: replace jokers has an issue as a client that requires interacting with the hostaged cop twice, first interact kills the joker and the second converts the new joker, lag can cause the interaction to kill both if you interact too fast, but not sure why it's immediately killing both...

**Comment by segabl** [comment]
probably the same reason then, but not related to jokermon. your game kills the joker, but hasn't received the message from the host that you're down one joker, so if you try to interact again your game still thinks you have 2 and kills off the other too

**Comment by Ravenous212** [comment]
Here's the thing: without jokermon (or rather the latest fix for it) it only kills off one joker unless you're interacting too fast, now it kills them both off upon the first interaction regardless of how fast you're pressing the button or how laggy the game is, again a minor problem since you're already converting another anyways, it's just annoying to deal with because you need to grab another afterward...

**Comment by segabl** [comment]
Yeah idk, I just don't see how they would conflict though. Maybe try giving replace jokers a higher/lower priority in the mod.txt

**Comment by Ravenous212** [comment]
Priority doesn't matter, like I said it's only a minor issue, you're likely going to be reconverting your jokers anyways, and this doesn't matter if you're hosting, only as a client, it's probably the closest you're gonna get with this for compatibility without spending a while on it, either way, the fixes are appreciated.
