### ISSUE TITLE
Revive All button doesn't work

### ISSUE THREAD

**Issue by morerokk** [segabl/pd2-jokermon#6]
The "revive all" button doesn't seem to work. It correctly deducts money and the notification goes away, but I still have fainted jokers. I have to individually revive them to get them back.

Here's a screenshot, I had revivable jokers but "revive all" didn't do anything: https://i.imgur.com/kGjPPg1.png

**Comment by segabl** [comment]
hmm that could probably have to do with them being in the negative hp, however that happened? are all the ones that didn't get revived negative?

**Comment by segabl** [comment]
Just checked and it indeed happens when they are below 0. Should be fixed in 4496a9615fc453aa8c803112fcd617d10caa0aab
