### ISSUE TITLE
Spawning Jokermon

### ISSUE THREAD

**Issue by DanicleV** [segabl/pd2-jokermon#7]
I don't know if there's a reason already given for this that I've missed, or a simple explanation I've failed to think of, but this is what I'm noticing. I can't seem to spawn in any of the Zeal Heavy Swat Jokers, from Death Sentence difficulty, into any other difficulty. I had thought maybe (With my complete lack of coding knowledge) the reason is because the models for those units are only present in Death Sentence? I obviously have no idea how specifically the mod or the game works in code, nor code in general, but I figured I'd at least bring this up in case you should be able to.

Side Note: Perfectly fine by me if you're NOT supposed to be able to use those in any difficulty lower, I'll just use Death Wish Jokers, as I've tested them to be spawnable in lower difficulties.

**Comment by segabl** [comment]
> I had thought maybe (With my complete lack of coding knowledge) the reason is because the models for those units are only present in Death Sentence?  

Yes, that is the reason. Death Sentence units are only loaded by the game when you play on that difficulty.

**Comment by DanicleV** [comment]
> > I had thought maybe (With my complete lack of coding knowledge) the reason is because the models for those units are only present in Death Sentence?
> 
> Yes, that is the reason. Death Sentence units are only loaded by the game when you play on that difficulty.

Oh wow I was right, well that's that then. Thanks for the info.
