### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by BowlerEXRS** [segabl/pd2-jokermon#8]
On start, the game just exits.
Attached i have the crash file
[crash.txt](https://github.com/segabl/pd2-jokermon/files/6245836/crash.txt)

**Comment by segabl** [comment]
Looks like you don't have [BeardLib](https://modworkshop.net/mod/14924) installed

**Comment by BowlerEXRS** [comment]
I do.
![Screenshot 2021-04-03 013119](https://user-images.githubusercontent.com/76852985/113461320-57533c80-941c-11eb-9d63-0c8c456ed755.png)

But it seems that the auto update didn't work and decided not to switch to 4.3, gonna go test that now

**Comment by BowlerEXRS** [comment]
Nope, still the same

**Comment by segabl** [comment]
everything in the correct folder? do you see the beardlib icon in the main menu?

**Comment by BowlerEXRS** [comment]
Yes i do, i also tried it just with the required mods and it didn't work as well.

**Comment by segabl** [comment]
can you upload the blt log and attach it here? you should be able to find it in mods/logs

**Comment by BowlerEXRS** [comment]
There are none?
Even after starting it again it doesn't generate one

**Comment by segabl** [comment]
hmm that sounds really weird. something might be wrong with your superblt installation then. there should always be at least one log file when you run the game

**Comment by BowlerEXRS** [comment]
Ok, i have been trying everything imaginable, even going as far as reinstalling steam and payday 2, but i wont get any log.
Might just be a "me" problem again. Anyway, thanks for your time, i doubt theres anything you can do about it.

**Comment by Ravenous212** [comment]
> Ok, i have been trying everything imaginable, even going as far as reinstalling steam and payday 2, but i wont get any log.
> Might just be a "me" problem again. Anyway, thanks for your time, i doubt theres anything you can do about it. 

Hate to re-open this, but it's peaked my curiosity... would it be possible to DM? I would like to see if we can get to the bottom of this, it sounds familiar but probably a different cause.

**Comment by BowlerEXRS** [comment]
If you want, sure. Where do u want to talk about this?

**Comment by Ravenous212** [comment]
Steam or discord, doesn't really matter that much to me, as long as direct communication is possible.

Edit: Thought I added the steam link, apparently not: https://steamcommunity.com/id/42151562/
