### ISSUE TITLE
Jokermon disables Keepers Joker Name mod names (And some other issues)

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-jokermon#9]
Hey!

I noticed that when using Jokermon, it disables Keepers Joker Names mod, meaning no random names a displayed above theyr heads

Before: (This is an old screenshot, but since removing WolfHud could cause some problems, i dint take ingame screenshot. But if you reguire a better one i will go and take one!)
![image](https://user-images.githubusercontent.com/32977052/123645568-20c86a80-d82f-11eb-860f-9895fd8ada7f.png)

After:
![20210628163857_1](https://user-images.githubusercontent.com/32977052/123645842-5b320780-d82f-11eb-8c9c-e207b2f122e3.jpg)

Also the orange outline on the cop is weird, i dont record having that previesly, maybe because they were automaticly spawned using that option? Not really an issue, just something odd.

Other issues: 
Specials can be shiny enemies. Shinyes are so rare that seeing them on specials is kinda annoying. Nothing major, but since you cant capture them its pointless to have them shiny.

In the "After" screenshot, i always seem to get Martin and Len as my jokers.  I have set the weight to 0 on all of them, and there are other Jokers that are qualifiet, but i still get these two i would say 98% of the time. Spawned manually and automaticly. Nothing major still, since i could just spawn a new one, but a nice quality of life could be that the Jokers could be more random when they spawn for the first time.

Please let me know if you have any other questions or how possible these changes could be!

Ben

**Comment by segabl** [comment]
Jokermon should work absolutely fine with Keepers Joker Names. Judging from the screenshot there might be an issue or conflict with another mod. In the past people have had issues with "Intimidated outlines" so if you have that mod try disabling it.

When you send out Jokers, they are sent out in the exact order as they are listed in the menu left to right, top to bottom, so changing the order there will also affect the order in which they are sent out.

Regarding shiny specials, it's something I'm aware of and kept in intentionally as a sort of "encounter shiny before you have pokeballs" reference.

**Comment by sirben99** [comment]
Hey!

Now Jokermon seems to be crashing every time i launch with only these mods:
![image](https://user-images.githubusercontent.com/32977052/123676830-174dfb00-d84d-11eb-924b-eee515bc1fd4.png)

Heres the crahslog:
[crash.txt](https://github.com/segabl/pd2-jokermon/files/6728130/crash.txt)

Removing WolfHud doesent help

Ben

EDIT: Wait, i dint install Beardlib, now game launches just fine.

EDIT 2: It seems that the problem persist even with those above mods only isntalled (Plus Beardlib):
![20210628201527_1](https://user-images.githubusercontent.com/32977052/123677359-b07d1180-d84d-11eb-804a-e0bb5c0a04ae.jpg)


EDIT 3: Deleting wolfhud dint work, idk if its a mod conflict, since none of these should do anything to cause this

EDIT 4: Okay so, deleting Jokermon dint solve it, this seems to be purely a Keeper Joker Names issue, unless Extra Profiles and Skill Sets somehow manages to mess it up

Mods folder: 
![image](https://user-images.githubusercontent.com/32977052/123678126-97c12b80-d84e-11eb-8c09-c26ca5d9ad48.png)

Ingame:
![20210628202252_1](https://user-images.githubusercontent.com/32977052/123678160-a4458400-d84e-11eb-88ea-a7ada25bc7e2.jpg)

EDIT 5: I seem to have confirmed that this issue is solely on Keeper Joker Names not working at all. This is my mod folder, nothing should conflict with it. My mod_overrites is not existing. I deleted Saves folder, nothing.

Mods:
![image](https://user-images.githubusercontent.com/32977052/123678856-83c9f980-d84f-11eb-8b93-555289c651fd.png)

Ingame Mods:
![20210628203013_1](https://user-images.githubusercontent.com/32977052/123678998-ab20c680-d84f-11eb-8986-839a9e1817de.jpg)


Ingame: 
![20210628202628_1](https://user-images.githubusercontent.com/32977052/123678873-8a587100-d84f-11eb-9cc0-5c93e22ffa8f.jpg)

**Comment by segabl** [comment]
Well, Keepers Joker Names requires you to have Keepers, otherwise it won't work.

**Comment by sirben99** [comment]
I accually just now realised that.. Welp, that was fun. Ill now see what could conflict

**Comment by sirben99** [comment]
I think i cracked it. When you convert someone, it shows a name. BUT, when you spawn someone in, theyr name doesent show.

![20210628204754_1](https://user-images.githubusercontent.com/32977052/123681171-25524a80-d852-11eb-9286-f8a3c47ea485.jpg)

The Blue officer is a spawned one, the guard is a converted one.

This is the mod list:
![image](https://user-images.githubusercontent.com/32977052/123681472-8ed25900-d852-11eb-8aa9-3b0c0190a784.png)

**Comment by segabl** [comment]
Hmm, both should work just fine. can you show me your Keepers settings?

**Comment by sirben99** [comment]
Sure, here:
![20210628211058_1](https://user-images.githubusercontent.com/32977052/123683925-7b74bd00-d855-11eb-8e45-d2fb54e007af.jpg)

I noticed that the Show names is off, but like in the above screenshot, it still shows in the newly captured one

**Comment by segabl** [comment]
yeah I figured it would be something like this. it's actually an issue where the show names option of keepers is not respected by keepers joker names. so if you turn show names on it should work as expected.

**Comment by sirben99** [comment]
Accually, funnilly enough i discovered something. If you send ur joker out and dont convert anyone, there is no name. E.g: Send them out in start of a heist and dont convert anymore else or call them back.

But if you instead convert someone FIRST, and then send out ur joker, they will have a name again:
![20210628211854_1](https://user-images.githubusercontent.com/32977052/123684707-782e0100-d856-11eb-8d5d-fb7199465a1a.jpg)

This is my joker after converting someone. If you dont, it will not have a name, as seen here: 
![20210628212035_1](https://user-images.githubusercontent.com/32977052/123684908-b6c3bb80-d856-11eb-96c3-d0f0076d4be6.jpg)

**Comment by segabl** [comment]
yeah this is due to how keepers names work. keepers joker names just changes the keepers name whenever the player starts a converting interaction. this also happens if show names is off, which technically is just an empty name. that's why you would get the last set name if you convert something first. so really, turning on "show names" is the recommended solution.

**Comment by sirben99** [comment]
Ah, ill try to turn it on and see what happens. I dont really remember why i turned it off in a first place

**Comment by sirben99** [comment]
Now everything works as intented! I accually remember now, since Keepers let you choose ur name, and i put John, every convert would be John. But with ur mod thats no longer the case, if you put the name blank.

Martin and Len can happily assist criming again!
![20210628212511_1](https://user-images.githubusercontent.com/32977052/123685571-8597bb00-d857-11eb-8f04-cb2f4f94afdd.jpg)

**Comment by sirben99** [comment]
Just to add a comment here about what you sayd earlyer about the send out order, would it be possible to profide an option to make it order intepentent? This is not a top priority, but would be nice if its something you would see could be a possiple thing to do. If you dont feel its something worth adding thats fine too!

And thank you for assisting in this matter!

Ben

**Comment by segabl** [comment]
It only depends on the order value if you sort by that. You can sort by a lot of different stuff so there should be something in there for you. If you want semi random order, sorting by EXP needed to level up (as long as they haven't reached 100) is a good way to get that effect.

**Comment by sirben99** [comment]
Ah, thank you for the answer! Ill try the values. You can close this issue now since its sorted. Thank you once more!
